
class BookLocators:
    TEXT_CATALOG = ('Каталог')
    TEXT_PLACEHOLDER = ('Поиск по каталогу')
    SEARCH_BTN = ('.search-btn')
    NAME_BOOK_KING = ('Ловец снов')
    IMG_BOOK = ('img')
    NAME_BOOK_LAVKRAFT = ('Дагон')
    PRICE_BOOK = ('870 руб.')
    ADD_TO_BASKET = ('Добавить в корзину')
    CREATE_ORDER = ('Оформить заказ')
    AUTHOR_LIST = ("ПисателиСтивен КингГерман ГессеГовард ЛавкрафтАртуро Перес-РевертеСтендальАртур ")
    BOOK_ROOM = ('О КнигиРум')
    DELIVERY = ('Партнерам по доставке')
    SELERS = ('Партнерам-селерам')
    HELP = ('Помощь')
    FAQ = ('FAQs')
